CREATE TABLE "data" (
	"id"	INTEGER NOT NULL UNIQUE,
	"data_1" INTEGER NOT NULL,
	"data_2" INTEGER NOT NULL,
	"data_3" INTEGER NOT NULL,
	"data_4" INTEGER NOT NULL,
	"data_5" INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);